// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi3exltswU5194TQLwauQslswmPCayd7s',
    appId: '1:339967277439:web:3ca691bf9232e09483824a',
    messagingSenderId: '339967277439',
    projectId: 'reejai-app',
    authDomain: 'reejai-app.firebaseapp.com',
    storageBucket: 'reejai-app.firebasestorage.app',
    measurementId: 'G-TXZS9S28GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd-WF48emiCdeOtH8IUSMRzUPOjgSbrcA',
    appId: '1:339967277439:android:eab2b7d98d0986ef83824a',
    messagingSenderId: '339967277439',
    projectId: 'reejai-app',
    storageBucket: 'reejai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINDtFdS-qhSh5SUadO36HAJB6yj7e-pc',
    appId: '1:339967277439:ios:f48ebecce04e371e83824a',
    messagingSenderId: '339967277439',
    projectId: 'reejai-app',
    storageBucket: 'reejai-app.firebasestorage.app',
    iosBundleId: 'com.example.reebJaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINDtFdS-qhSh5SUadO36HAJB6yj7e-pc',
    appId: '1:339967277439:ios:f48ebecce04e371e83824a',
    messagingSenderId: '339967277439',
    projectId: 'reejai-app',
    storageBucket: 'reejai-app.firebasestorage.app',
    iosBundleId: 'com.example.reebJaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi3exltswU5194TQLwauQslswmPCayd7s',
    appId: '1:339967277439:web:ee78082f3c94ab7d83824a',
    messagingSenderId: '339967277439',
    projectId: 'reejai-app',
    authDomain: 'reejai-app.firebaseapp.com',
    storageBucket: 'reejai-app.firebasestorage.app',
    measurementId: 'G-K1LRP329H8',
  );
}
